### ISSUE TITLE
Cambiar el backend

### ISSUE THREAD

**Issue by gabrieldelaparra** [hvarg/RDFExplorer#5]
Hola @hvarg,

Te había escrito en otro Issue. Está super bueno el sistema !
Me gustaría usar el sistema con un backend distinto. 
Crees que podríamos hablar? (No se si dejar correo o wsp aqui :/)
Podrías enviar tu contacto a través de tu profe o Aidan? 
Saludos !

**Comment by hvarg** [comment]
Si, no debería haber problema cambiando el backend, la mayoría de la logica está del lado cliente y el backend solo manda datos.

Si quieres hablar con mas detalles del asunto puedes escribirme a hern.var@gmail.com

Saludos!
